workflows:
  android-release:
    name: Android Release

    environment:
      java: 17

    scripts:
      - gradle assembleRelease
      - gradle bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
